### ISSUE TITLE
Implement `Tables.partitions(t::LazyTree)`

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/UnROOT.jl#114]
A prototype implementation has been shown at https://gist.github.com/aminnj/79ceeb7ab9026f80e3cc1978124f8370 by @aminnj 

The use case when the analysis is highly columnar (but not single column), users can potentially gain by having SIMD, so imagine computing invariant mass using two columns:
```julia
for table in Tables.partitions(t::LazyTree)
   mass.(table.lep1, table.lep2)
   # or
   @simd for row in table
       compute(row.blah1, row.blah2)
   end
end
```

in this case, the columns of inner `table` has to be contiguous in RAM (then we hope compiler is smart). Actually, @oschulz can you confirm `TypedTable` of `VectorOfVectors` is SIMD-able at all?

**Comment by Moelf** [comment]
In fact, I don't know how to SIMD if a single `row` of `table` is bigger than SIMD size (256/512 bits?)

**Comment by oschulz** [comment]
> @oschulz can you confirm TypedTable of VectorOfVectors is SIMD-able at all?

SIMD for `VectorOfVector`'s columns in a `TypedTables.Table` is not straightforward, because there are two loops involved. But it definitely works for scalar-valued columns (quite an important use case too, after all).

The main advantage of using `VectorOfVector`s will be the ability to use `flatview`, `deepmap`, `adapt(CuArray, table)` and so on.

**Comment by oschulz** [comment]
I should probably also add support for Functors.jl to ArraysOfArrays.jl, to enable `fmap` and `functor`.

**Comment by Moelf** [comment]
>works for scalar-valued columns

yeah but in that case I don't see advantage of `for table in partition(ttree)` because:
1. If you're using scalar column, just do it on the original tree: `ttree.scalar1`
2. If many branches are loaded, the inner `for row in table` will stop SIMD for either VoV or because too many columns

**Comment by aminnj** [comment]
Before I forget to mention it. There are a couple things to note about the above `partitions()` implementation.
1. We should have a more robust way to determine good partitions. I've only ever seen the `fCluster` stuff in NanoAOD. Haven't checked what uproot does, but they have the option for a maximum memory step size in `iterate()`. That's a good idea and calculable from the `TBranch` fields I think.
2. When I tried to do `Arrow.write()` with the partitions, I was eating up all the RAM on my machine. This is because even if you set `ntasks=1`, there's a `@sync`/`@async` for the writing step, which means the LazyBranch will vigorously read baskets from disk faster than they can be written. I ended up using the `Tables.partitioner()` API and putting a `lock()`/`unlock()` around the file to not blow up my RAM.

**Comment by oschulz** [comment]
>  I don't see advantage of for table in partition(ttree) for analysis because [...]

It'll still be nice to have it, since it gives users more power to optimize the processing of the chunks (since it makes them explicit), without them having to worry about splitting the index range and how big to make the partitions.

Also, it allows for writing broadcasts over the columns/branches, which may be SIMDed even for a larger number of cols.

> If you're using scalar column, just do [...] If many branches are loaded [...]

Sure, but I often have use cases when I need a access just a small number of branches/columns, and there SIMD would work nicely.

**Comment by oschulz** [comment]
> When I tried to do Arrow.write() with the partitions, I was eating up all the RAM on my machine

Hm, when the writes are done within the ```for tbl in partitions(mytree``` loop, then each write should block further reading, right (if the write is blocking)?

That's of course not the path to maximum throughput though, since we'd want to read, write and process all at the same time. There may be a fairly easy way, though, by adding a back-pressure mechanism: Lazy reading allows us to read and process at the same time, by using limited read-ahead. Lazy (i.e. non-blocking writing) could add backpressure in the loop-over-partitions model by blocking if the write-queue reaches a certain length.

**Comment by oschulz** [comment]
If we implement `Tables.partitions` (with a mechanism that robustly chooses a "good" partition size), we could actually use that internally in the loop-implementation over whole trees. Could make things nicely consistent, internally and externally.

**Comment by Moelf** [comment]
>since it gives users more power to optimize the processing of the chunks

isn't "processing by chunk" a workaround to the slow-for-loop problem in Python? I recall this ever being a thing/desired pattern in C++ ROOT.

>we could actually use that internally in the loop-implementation over whole trees

the `iterate(tree)` loop doesn't need to partition across all branches thus doesn't have this problem. each branch is individually accessed with whatever event number we're.

**Comment by oschulz** [comment]
> isn't "processing by chunk" a workaround to the slow-for-loop problem in Python?

No, we'd still loop over the content of the chunks Julia-fashion, etc. This is not about Python-style "vectorization", it's more about mapping the processing model to what current hardware likes, to me.

**Comment by oschulz** [comment]
> The iterate(tree) loop doesn't need to partition across all branches thus doesn't have this problem. each branch is individually accessed with whatever event number we're at.

Ah, right. Ok, then for looping over the whole tree "row-by-row" that's ideal.

But for use that require more control or column-wise in-memory data (we do signal processing and so on), it would be very helpful to have `partitions` that "synchronize" the chunks across the (active) branches.

**Comment by oschulz** [comment]
It kinda depends on what's done per entry, I would say - if the operation per entry is somewhat expensive, iterating over the tree row-by-row will be great. For use cases where computation per entry is relatively cheap, we do want to offer user-accessible columnar memory-layout.

**Comment by Moelf** [comment]
on the basis that we will get functional `partitions()`

>relatively cheap, we do want to offer user-accessible columnar memory-layout.

but why? "partition" implies the user is iterating over some large range. If what they need fits in RAM, they can just work with a materialized table. And since they are iterating over some range, why would the computation being cheap or expensive matter? iterate event-by-event isn't expensive to begin with.
Expecially:
>we'd still loop over the content of the chunks Julia-fashion, etc. This is not about Python-style "vectorization"

that makes me think of a double loop:
```julia
hist = ...
for subtable in partitions(mytree)
	for row in subtable # <--- notice if subtable is wider than 2 column, you lose SIMD
		push!(hist, row.leppt)
	end
end
```

**Comment by oschulz** [comment]
> relatively cheap, we do want to offer user-accessible columnar memory-layout.

Let's say (just an example from my own practice) that I want to do signal processing, signals and other information I need are stored in a few branches. I do want to run FFT on the signals, and other stuff, but I need information from some other branches too for that. But FFT only becomes really efficient (esp. on GPUs) if you do more than one signal at a time. So I want to have partitions (my whole file can be 10 GB or larger), and I want these partitions to be synchronized across branches, and I want to have them "in hand" (not hidden behind an  iteration mechanism over the whole tree).

**Comment by oschulz** [comment]
So I do want to have that double loop (and the inner loop may or may not be offloaded to a different computing hardware, even).

**Comment by Moelf** [comment]
I'd consider moving to GPU similar to writing to disk in the sense that you want to fully copy the data , somewhere, in aligned chunks. And I can totally see that being useful! Btw there's no "unsynced" ever, in looping, you're just accessing one event, and once you have a part of the table, it will be concrete.

**Comment by oschulz** [comment]
> Btw there's no "unsynced" ever, in looping

Ah - with "synced" I meant chunks that cover the same events for each branch, in comparison to the internal chunks that (if I understand correctly) store the current basket for each branch, so each cached chunk covers different events.

**Comment by oschulz** [comment]
I should have said "aligned", not "synched".

**Comment by aminnj** [comment]
Ignoring the issue with `Arrow.write` async for writing, the linked PR now lets us do

```julia
julia> using UnROOT, Tables

julia> const t = LazyTree(ROOTFile("Run2012BC_DoubleMuParked_Muons.root"),"Events",["nMuon","Muon_pt"]);

julia> mykernel(x) = length(x.Muon_pt);

julia> @time mapreduce(kernel, +, Tables.partitions(t))
 12.517621 seconds (221.90 k allocations: 7.990 GiB, 9.91% gc time, 0.46% compilation time)
149322456
```
where the partitions are aligned across all requested branches. As far as I understand, the typical size of a cluster is 30MB since that's a ROOT AutoFlush default somewhere, so it's pretty safe to use these partitions. And since we have the byte counts for each chunk, we can consider combining them into larger chunks if it makes `mykernel` more efficient.
